--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekEatHeal
build-by-default: true
branches:
- main
projects:
  KygekEatHeal:
    path: ""
    libs:
    - src: JackMD/UpdateNotifier/UpdateNotifier
      version: ^2.1
...
